/*
 * © Copyright Lenovo 2015.
 *
 * LIMITED AND RESTRICTED RIGHTS NOTICE:
 *
 * If data or software is delivered pursuant a General Services Administration
 * "GSA" contract, use, reproduction, or disclosure is subject to
 * restrictions set forth in Contract No. GS-35F-05925.
*/
define({
    "root": {
    	"cancel_job_confirm": "确定要取消这个作业吗?",
    	"confirm": "确认",
    	"cancel": "取消",
    	"rerun_job_confirm": "确定要重新运行此作业吗?",
    	"delete_finish_job_confirm": "确定要将此作业从列表中删除吗?",
    	"edit_job": "编辑作业",
    	"job_name": "作业名",
    	"job_file": "作业文件",
    	"queue_name": "队列名",
    	"please_select": "请选择",
    	"working_dir": "工作目录",
    	"browse": "浏览",
    	"output_path": "输出路径",
    	"std_input_output": "标准输入输出",
    	"MPI_prog": "MPI程序",
    	"res_req": "资源需求",
    	"CPU_core_num": "CPU核数",
    	"core": "核",
    	"nodes_num": "节点数",
    	"available": "个(可用)",
    	"share": "共享",
    	"exclusive": "独享",
    	"mem_size": "内存容量",
    	"giga": "G(2G可用)",
    	"walltime": "预计运行时间",
    	"hours": "300小时",
    	"status_notify": "运行状态通知",
    	"finish": "完成",
    	"suspend": "挂起",
    	"mail": "邮件",
    	"phone": "手机",
    	"exec_command": "可执行命令",
    	"job_id": "作业ID",
    	"qtime": "提交时间",
    	"endtime": "退出时间",
    	"queue": "队列",
    	"run_time": "运行时长",
    	"hour": "小时",
    	"min": "分",
    	"waittime": "等待时长",
    	"status": "状态",
    	"waiting": "等待排队",
    	"holding": "保留",
    	"queueing": "排队",
    	"rund_time": "已运行时间",
    	"action": "操作",
    	"rerun": "再次运行",
    	"job_cancel_fail": "作业取消失败",
    	"job_cancel_success": "作业已取消",
    	"job_rerun_fail": "作业提交失败",
    	"job_rerun_success": "作业提交成功",
    	"del": "删除",
    	"job_delete_fail": "作业删除失败",
    	"success": "成功",
    	"failed": "失败",
        "uploadFiles": "上传文件",
        "job_detail":"作业详情",
        "running_label":"运行",
    	"wait_for_running_label":"等待",
    	"finished_label":"结束",
        "exechosts":"执行节点",
        "viewjobdetail":"查看详细",
        "canceljob":"取消作业",
        "starttime":"开始时间",
        "primary_id":"ID",
        "second":"秒"
    },
    "zh": true,
	"en": true
});