/*
 * © Copyright Lenovo 2015.
 *
 * LIMITED AND RESTRICTED RIGHTS NOTICE:
 *
 * If data or software is delivered pursuant a General Services Administration
 * "GSA" contract, use, reproduction, or disclosure is subject to
 * restrictions set forth in Contract No. GS-35F-05925.
*/
define({
    "root": {
      "submitJob": "提交作业",
      "MatlabPattern": "Matlab模版",
      "template":"模板",
      "CADPattern": "CAD模版",
      "testPattern": "碰撞测试模版",
      "analyzePattern": "力学分析模版",
      "jobID": "作业ID",
      "jobName": "作业名",
      "jobFile": "作业文件",
      "browse": "浏览",
      "createJobFile": "创建作业文件",
      "confirm": "确认",
      "cancel": "取消",
      "createJob": "创建作业",
      "queue": "队列",
      "selectOption": "请选择",
      "workDir": "工作目录",
      "outputPath": "输出路径",
      "outputs": "标准输出和错误输出",
      "MPIProg": "MPI程序",
      "resReq": "资源需求",
      "CPUCoreNum": "每个节点的CPU核数",
      "cores": "核",
      "nodeNum": "节点数",
      "nodes": "个",
      "mega": "M",
      "share": "共享",
      "exclusive": "独享",
      "memSize": "内存容量",
      "giga": "G",
      "walltime": "预计运行时间 ",
      "time": "300小时机时配额可用",
      "statusNotify": "运行状态通知",
      "finish": "完成",
      "suspend": "开始执行",
      "email": "邮箱",
      "phone": "手机",
      "exeCommand": "可执行命令",
      "submit": "提交",
      "pbs": ".pbs , .sh etc.",
      "close": "关闭",
      "jobCreateSuccessfully": "作业提交成功",
      "jobCreateFailed": "作业提交失败, 请检查程序",
      "mpi_example": "示例：a.out  etc",
      "mpi_arg_example": "示例：-t -h",
      "MPIArg": "MPI运行参数",
      "hour": "小时",
      "minute": "分",
      "mail_notice": "多个邮箱请用分号;分隔",
      "ajaxError": "网络通信错误",
      "errMsg": "错误信息",
      "chooseFolder": "选择文件夹",
      "chooseFile": "选择文件",
      "jobNameEmptyMsg": "请输入作业名",
      "jobNameRegMsg": "字母、数字、下划线组成，4-16位",
      "queueEmptyMsg": "请选择队列",
      "workingDirEmptyMsg": "请选择目录",
      "MPIProgEmptyMsg": "请选择文件",
      "intReqMsg": "请输入正整数",
      "minMsg": "请输入0-59之间的正整数",
      "mailMsg": "请输入正确的邮件格式xxx@xxx.xx",
      "jobFileEmptyMsg": "请选择作业文件",
      "uploadFiles": "上传文件",
      "work_dir_notify": '请点击"浏览"按钮选择目录',
      "MPI_prog_notify": '请点击"浏览"按钮选择程序'
    },
    "zh": true,
	"en": true
});