define({
        "reporForm":"Report",
        "listHeader":"Template",
        "jobReport":"Job report",
        "jobReportStat":"Job statistics report",
        "jobReportDetail":"Job details report",
        "alarmReport":"Alarm report",
        "alarmReportStat":"Alarm statistics report",
        "alarmReportDetail":"Alarm details report",
        "logReport":"Operation report",
        "logReportDetail":"Operation details report",
        "time":"Time：",
        "time_title":"Time period",
        "filter":"Filter",
        "format":"Report format",
        "function":"Mode：",
        "init":"Predefine",
        "custom":"Custom",
        "timeFunc":"init",
        "timeHour":"Last 1 hour",
        "timeDay":"Last 1 day",
        "timeWeek":"Last 7 days",
        "timeMonth":"Last 30 days",
        "startTime":"Start time",
        "endTime":"End time",
        "type":"job",
        "userName":"User：",
        "nodeName":"Node：",
        "billName":"Bill group：",
        "userNameInfo":"Please enter user name",
        "nodeNameInfo":"Please enter node name",
        "billNameInfo":"Please enter bill group name",
        "choosable":"Optional",
        "fromatHeader":"Format：",
        "header":"Job statistics report",
        "submit":"Submit",
        "allLevel":"All",
        "error":"Fatal",
        "danger":"Error",
        "warn":"Warn",
        "info":"Info",
        "level":"Alarm level：",
        "node":"Node：",
        "nodeInfo":"Default all",
        "infos":"Stat",
        "emptyTime":"Please select time",
        "downLoadError":"Download failed",
        "inputInfo":"Comma separated",
        "nodeReportStat":"Node statistics report",
        "nodeReportDetail":"Node details report",
        "userReportStat":"User statistics report",
        "userReportDetail":"User details report",
        "billReportStat":"Bill group statistics report",
        "billReportDetail":"Bill group details report"
    });