define({
		"ansysName":"New Ansys Job",
		"comsolName":"New Comsol Job",
		"mpiName":"New MPI Job",


		"jobScheduleTitle":"Job Schedule Parameters",
		"paraNodes":"Nnodes",
		"paraQueue":"Queue",
		"paraCore":"Cores/Node",
		"paraName":"Name",
		"paraWall":"Wall Time",
		"paraWin":"WinScp File Manager",
		"paraWeb":"Web File Manager",

		"runParaTitle":"Run Parameters",
		"paraMPIType":"MPI Type",
		"paraRemoteShell":"Remote Shell",
		"paraCommunicate":"Communication",
		"paraOtherPara":"Other Paramaters",
		"paraMPIEnvfile":"MPI Envfile",
		"browse":"Browse",
		"paraMPIProgram":"MPI Program",
		"paraArguments":"Arguments",
		"paraWorkingDIR":"WorkingDIR",
		"paraOutputFile":"Output File",

		"advancedParaTitle":"Advanced Parameters",
		"paraPBSOptions":"PBS Options",
		"paraMPIOptions":"MPI Options",
		"paraPreCommands":"Pre Commands",
		"paraPostCommands":"Post Commands",
		"Infini":"Infini",
		"BandTCP":"BandTCP",
		"ShareMemory":"Share Memory",
		"CPUBinding":"CPU Binding",

		"envParaTitle":"Environment Parameters",
		"paraVersion":"Version",
		"paraPareMode":"Parallel Mode",
		"paraPrecision":"Precision",
		"paraPrecisionDouble":"Double",
		"paraPrecisionSingle":"Single",
		"paraMemory":"Memory",
		"paraKeyFile":"Keyword File",
		"paraOutputLog":"Output Log",

		"paraRunMod":"Run mod",
		"paraInputType":"Input Type",

		
		"reset":"Reset",
		"submitJob": "Submit Job",
      "MatlabPattern": "Matlab Template",
      "CADPattern": "CAD Template",
      "testPattern": "碰撞测试模版",
      "analyzePattern": "力学分析模版",
      "jobID": "Job ID",
      "jobName": "Job Name",
      "jobFile": "Job File",
      "browse": "Browse",
      "createJobFile": "Create",
      "confirm": "OK",
      "cancel": "Cancel",
      "createJob": "Create Job",
      "queue": "Queue",
      "selectOption": "please select",
      "workDir": "Work Directory",
      "outputPath": "Output Path",
      "outputs": "standard output and error output",
      "MPIProg": "MPI Program",
      "resReq": "Resource Required",
      "CPUCoreNum": "CPUs/Node",
      "cores": "cores",
      "nodeNum": "Node Count",
      "nodes": "",
      "share": "Share",
      "exclusive": "exclusive",
      "memSize": "Memory Size",
      "giga": "G",
      "mega": "M",
      "walltime": "Estimated Time ",
      "time": "300 hours available",
      "statusNotify": "Status Notification",
      "finish": "finish",
      "suspend": "suspend",
      "email": "Email",
      "phone": "phone",
      "exeCommand": "execute command",
      "submit": "Submit",
      "pbs": ".pbs , .sh etc.",
      "close": "Close",
      "jobCreateSuccessfully": "Job is submitted successfully.",
      "jobCreateFailed": "Fail to submit the job, please check the program",
      "mpi_example": "Example：a.out  etc",
      "mpi_arg_example": "Example：-t -h",
      "MPIArg": "MPI Run Arguments",
      "hour": "hours",
      "minute": "minutes",
      "mail_notice": "split the emails with semicolon if more than one email address ",
      "ajaxError": "network communication error",
      "errMsg": "Error message",
      "chooseFolder": "select directory",
      "chooseFile": "Select file",
      "jobNameEmptyMsg": "please enter job name",
      "jobNameRegMsg": "4-16 characters. Letter number and _ are allowed.",
      "queueEmptyMsg": "Please select queue",
      "workingDirEmptyMsg": "Please select work directory",
      "MPIProgEmptyMsg": "Please select program",
      "intReqMsg": "Please enter  positive integer",
      "minMsg": "Please enter  positive integer between 0 to 59",
      "mailMsg": "Please enter correct email address xxx@xxx.xx",
      "jobFileEmptyMsg": "Please select job file",
      "uploadFiles": "upload file",
      "work_dir_notify": 'Click "Browse" to select directory',
      "MPI_prog_notify": 'Click "Browse" to select program',
      "textEmptyMsg":"please enter correct string",
      "requiredMsg":"It's required"
	});