/*
 * © Copyright Lenovo 2015.
 *
 * LIMITED AND RESTRICTED RIGHTS NOTICE:
 *
 * If data or software is delivered pursuant a General Services Administration
 * "GSA" contract, use, reproduction, or disclosure is subject to
 * restrictions set forth in Contract No. GS-35F-05925.
*/
define({
		"strategy-title":"Alarm Setting",
		"s_left_title":"Policy",
		"s_right_title":"Mail/SMS/Wechat",
		"s_script_title":"Script",
		"add":"Add",
    	"policy_id":"Alarm id",
		"policy_name":"Alarm name",
		"policy_level":"Alarm level",
		"status":"Status",
		"operation":"Operation",
		"enabled":"Open",
		"unabled":"Closed",
		"confirm":"Confirm",
		"cancel":"Cancel",
		"alarmwarn":"Warn",
    	"alarm_edit":"edit",
		"alarmdelete":"Delete",
		"alarmText":"Are you sure you want to delete this alert policy?",
		"add_title":"Add alarm policy",
		"edit_title":"Modify alarm policy",
		"email_title":"Test Mail",
		"phone_title":"Test SMS",
		"receive_email":"Recipient mailbox",
		"alarm_name":"4-16 character of the beginning of a letter or character, Not null",
		"alarm_threshold":"1-5 digit",
		"alarm_time":"1-8 digit",
		"alarm_mail":"E-mail error",
		"alarm_mail_mul":"邮箱地址不正确，长度应小于250",
		"alarm_phone_mul":"手机号码不正确，长度应小于250",
		"alarm_phone":"Phone number error",
		"email":"E-mail",
		"on":"Open",
		"off":"Close",
		"username":"User",
		"psw":"Password",
		"smtp":"SMTP",
		"smtp_port":"SMTP port",
		"send_email":"Email sender",
		"test_email":"Test E-mail",
		"phone":"SMS",
		"port":"Serial port",
		"modem":"Modem",
		"num_max":"Daily SMS limit",
		"test_phone":"Test SMS",
		"email_con":"Mail title",
		"email_content":"Mail content",
		"email_warn":"Your mail server configuration is successful!",
		"phone_num":"Phone number",
		"phone_content":"SMS content",
		"phone_warn":"LiCO test SMS: your SMS Modem configured successfully",
		"warn_smtp":"Please enter SMTP address",
		"warn_email":"Please enter your email address",
		"test_e":"LiCO test mail",
		"warn_phone":"Please enter phone number",
		"nameDefaultValue":"Please enter a SMTP login name",
		"pwdDefaultValue":"Please enter SMTP login password",
		"placeholder_name":"Please enter a new alarm name",
		"alarmMonitor":"monitor control index",
		"alarmCPU":"CPU使用率(%)",
		"alarmTemp":"温度(℃)",
		"alarmNerwork":"网络状况",
		"alarmDisk":"磁盘利用率(%)",
		"alarmElectric":"耗电量(W)",
    	"alarmHardware":"Hardware failure",
		"alarmCondition":"Condition",
		"alarm_gt":">",
		"alarm_lt":"<",
		"alarm_eq":"=",
		"alarm_duration_time":"Duration",
		"alarm_second":"Second",
		"alarm_monitornodes":"Monitoring node",
		"alarm_placeholdernodes":"Comma separated.",
		"alarm_fatal":"Fatal",
		"alarm_error":"Error",
		"alarm_warn":"Warn",
		"alarm_info":"Info",
		"alarm_noticetype":"Notice",
		"alarm_placeholdermail":"E-mail address,Comma separated.",
		"alarm_placeholderphone":"Phone number,Comma separated.",
		"alarm_on":"Open",
		"alarm_off":"Close",
		"empty":"Not null",
		"warn_port":"Please enter SMTP port",
		"save_success":"Successfully",
		"send_success":"Successfully",
		"save_error":"Failed",
		"send_error":"Failed",
		"chat":"Wechat",
		"appID":"appID",
		"appsecret":"appsecret",
		"Token":"Token",
		"test_chat":"Test Wechat",
		"chat_content":"Wechat content",
		"chat_warn":"LICO test Wechat：Wechat configured successfully",
		"alarm_policymail":"E-mail",
		"alarm_policyphone":"SMS",
		"alarm_policyvoice":"Ring",
		"alarm_policyscript":"Script",
		"alarm_policy_please":"Please select script",
		"alarm_script_upload":"Upload",
		"alarm_script_download":"Download",
		"set_script_file":"Set script",
		"alarm_script_fileText":"Click Browse to select the file",
		"alarm_browse":"Browse",
		"set_script_type":"Script type",
		"alarm_script_fileType":"Please select script type",
		"alarm_scriptTypr_none":"Unknown",
		"script_name":"Script name",
		"script_size":"Size",
		"script_modifyTime":"Time",
		"script_edit":"Edit",
		"alarm_script_rename_title":"Rename",
		"alarm_script_rename_text":"Redefine the script name",
		"preservation":"Save",
		"alarm_script_warn":"Are you sure you want to delete this script？",
		"alarm_null":"无",
		"alarm_ssl":"SSL",
		"alarm_tls":"TLS",
    	"alarm_script_rename_please": "已存在，请重新命名",
        "loading":"正在加载...",
        "qr_error":"二维码加载失败",
        "click_qr":"请点击图片重新加载",
        "see":"浏览",
        "qr_focus":"关注公众号，可获取实时的报警信息",
        "choose":"请选择文件",
        "email_fail":"邮件报警不可用,请点击重新加载!",
        "sms_fail":"短信报警不可用,请点击重新加载!",
        "chat_fail":"微信报警不可用,请点击重新加载!",
        "alarm_p_name":"报警名称不可以重复或者不能为空",
        "sended":"短信已发送数",
        "alarm_textareaLen":"长度应小于250"
});