/*
 * © Copyright Lenovo 2015.
 *
 * LIMITED AND RESTRICTED RIGHTS NOTICE:
 *
 * If data or software is delivered pursuant a General Services Administration
 * "GSA" contract, use, reproduction, or disclosure is subject to
 * restrictions set forth in Contract No. GS-35F-05925.
*/
define({
	"cancel_job_confirm": "Do you cancel the job?",
	"confirm": "Confirm",
	"cancel": "Cancel",
	"rerun_job_confirm": "Do you re-run the job?",
	"delete_finish_job_confirm": "Do you want to delete the job?",
	"edit_job": "Edit Job",
	"job_name": "Job Name",
	"job_file": "Job File",
	"queue_name": "Queue Name",
	"please_select": "please select",
	"working_dir": "Working Directory",
	"browse": "browse",
	"output_path": "output path",
	"std_input_output": "stdandard input-output",
	"MPI_prog": "MPI program",
	"res_req": "resource required",
	"CPU_core_num": "CPU core count",
	"core": "core(s)",
	"nodes_num": "Node Count",
	"available": "(available)",
	"share": "Share",
	"exclusive": "Exclusive",
	"mem_size": "Memory Size",
	"giga": "G(2G available)",
	"walltime": "wall duration",
	"hours": "300 hours",
	"status_notify": "status notification",
	"finish": "finish",
	"suspend": "suspend",
	"mail": "mail",
	"phone": "Phone",
	"exec_command": "execute Command",
	"job_id": "Job ID",
	"qtime": "Submit Time",
	"endtime": "End Time",
	"queue": "Queue",
	"run_time": "Run Duration",
	"hour": "hour(s)",
	"min": "minute(s)",
	"waittime": "Waiting Time",
	"status": "Status",
	"waiting": "Waiting",
	"holding": "Holding",
	"queueing": "Queueing",
	"rund_time": "Elapsed Time",
	"action": "Operations",
	"rerun": "re-run",
	"job_cancel_fail": "fail to cancel the job",
	"job_cancel_success": "the job is cancelled",
	"job_rerun_fail": "fail to submit the job",
	"job_rerun_success": "Job is submitted successfully",
	"del": "Delete",
	"job_delete_fail": "fail to delete the job",
	"success": "success",
	"failed": "failed",
	"uploadFiles": "uplaod files",
     "job_detail":"Job detail",
     "running_label":"Running",
 	 "wait_for_running_label":"Waiting for run",
 	"finished_label":"Finished",
     "exechosts":"Exec Hosts",
     "viewjobdetail":"View detail",
     "canceljob":"Cancel Job",
     "starttime":"Start time",
     "primary_id":"ID",
     "second":"second"
});