/*
 * © Copyright Lenovo 2015.
 *
 * LIMITED AND RESTRICTED RIGHTS NOTICE:
 *
 * If data or software is delivered pursuant a General Services Administration
 * "GSA" contract, use, reproduction, or disclosure is subject to
 * restrictions set forth in Contract No. GS-35F-05925.
*/
define({
	"allNodesTitle":"All Nodes",
	"nodeName":"Name",
	"nodeStatus":"Status",
	"nodeType":"Type",
	"managementIP":"BMC IP",
	"OSIP":"OS IP",
	"CPUCores":"CPUs",
	"usedMemory":"Used Mem",
	"totalMemory":"Total Mem",
	"usedStorage":"Used Storage",
	"totleStorage":"Total Storage",
	"CPUCoreUnit":"Cores",
	"showAllStatus":"All Status",
	"showAllType":"All Type",
	"nodesCount":"Nodes' Num",
	"offStatus":"Shutdown",
	"busyStatus":"Busy",
	"workingStatus":"Occupied",
	"idleStatus":"Free",
	"headNodeType":"Head Node(s)",
	"computeNodeType":"Compute Node(s)",
	"gpuNodeType":"GPU Node(s)",
	"ioNodeType":"I/O Node(s)",
	"loginNodeType":"Login Node",
	"groups": "Custom group",
	"monitor_WebSSH":"SSH",
	"monitor_WebKVM":"iConsole",
	"monitor_turn_off":"Off",
	"monitor_turn_on":"On",
	"monitor_turn_on_off":"Power",
	"monitor":"Monitor",
	"job":"Job",
	"select_time":"Please select period",
	"hour":"Last an hour",
	"day":"Last 1 day",
	"seven":"Last 7 days",
	"month":"Last 30 days",
	"listview":"List View",
	"please_select_period_of_time":"Please select period",
	"past_one_hour":"Last an hour",
	"past_one_day":"Last 1 day",
	"past_one_week":"Last 7 days",
	"past_one_month":"Last 30 days",
	"success_turn_on":"Successfully",
	"error_turn_on":"Failed",
	"success_turn_off":"Successfully",
	"error_turn_off":"Failed",
	"prompt_node_details":"Node detail",
    "prompt_power_on":"Open",
	"prompt_power_off":"Shutdown",
	"prompt_kvm":"iConsole",
	"systerm_monitor":"Monitor",
	"running_jobs":"Job",
	"prompt_ssh":"SSH",
	"present":"Unconfirmed",
	"confirm":"Unfixed",
	"solve":"Fixed",
	"alarm_btn":"Alarm",
	"alarm_id":"ID",
	"alarm_name":"Alarm name",
	"alarm_level":"Level",
	"alarm_status":"Status",
	"alarm_time":"Time",
	"alarm_nodes":"Node",
	"serviceNodeType":"Service Node"
});